export const CREATE_ORDER_REQUEST ="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCES ="CREATE_ORDER_SUCCES";
export const CREATE_ORDER_FAIL ="CREATE_ORDER_FAIL";

export const MY_ORDER_REQUEST ="MY_ORDER_REQUEST";
export const MY_ORDER_SUCCES ="MY_ORDER_SUCCES";
export const MY_ORDER_FAIL ="MY_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST ="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCES ="ORDER_DETAILS_SUCCES";
export const ORDER_DETAILS_FAIL ="ORDER_DETAILS_FAIL";