export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCES ="ALL_PRODUCTS_SUCCES";
export const ALL_PRODUCTS_FAIL ="ALL_PRODUCTS_FAIL";


export const PRODUCTS_DETAILS_REQUEST ="PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCES ="PRODUCTS_DETAILS_SUCCES";
export const PRODUCTS_DETAILS_FAIL ="PRODUCTS_DETAILS_FAIL";

export const CLEAR_ERROR ="CLEAR_ERROR";
