export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCES = "REGISTER_SUCCES";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCES = "LOAD_SUCCES";
export const LOAD_FAIL = "LOAD_FAIL";

export const LOGOUT_USER = "LOGOUT_USER"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCES = "UPDATE_PROFILE_SUCCES";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCES = "UPDATE_PASSWORD_SUCCES";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCES = "FORGET_PASSWORD_SUCCES";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";


export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCES = "RESET_PASSWORD_SUCCES";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";